### ISSUE TITLE
数据接口异常请求

### ISSUE THREAD

**Issue by mosquitokevin** [Krstar233/IceWineManageSystem#1]
请问大佬这个项目的环境要怎么配置啊 急急急

**Comment by mosquitokevin** [comment]
我用的是IDEA

**Comment by mosquitokevin** [comment]
@Krstar233 @Yasuosword @ZaynWong 可以解答一下嘛

**Comment by Krstar233** [comment]
demo/api/conn.php 配置了数据库连接信息，需要配置 mysql 建个库
---
demo/api/conn.php:

$hostname = "localhost";
$username = "root";
$database = "iceman";
$password = "";
$conn = mysqli_connect($hostname, $username, $password);
$db = mysqli_select_db($conn, $database);
---
建库的 SQL 语句在 database/iceman.sql

**Comment by mosquitokevin** [comment]
我数据库都已经建立好了 连接应该也是正常的 貌似是.py的那个文件显示找不到order.csv

**Comment by mosquitokevin** [comment]
大佬可以加个联系方式询问嘛55555555
![Uploading _VK)YYPKZ`JBYZ2})R4J{}X.png…]()

**Comment by mosquitokevin** [comment]
@Krstar233 跪求大佬求助

**Comment by Krstar233** [comment]
sorry，工作在忙。你的这个图片我打不开，可以麻烦详细描述一下报错信息吗？

**Comment by Krstar233** [comment]
@mosquitokevin 同学是用 windows 系统吗？建议 windows 系统可以配置 Wamp 集成作为 PHP 的环境哈。当时这个课程作业用的就是这个环境，然后数据库可以直接使用 Wamp 环境的 phpMyAdmin 导入 SQL 语句就好了。

**Comment by mosquitokevin** [comment]
@Krstar233 我是使用的Wamp 然后也是导入的了 现在应该是接口的问题 不知道应该怎么调 因为没有学习过php

**Comment by mosquitokevin** [comment]
@Krstar233 现在就是/data中的readcsv.py文件运行不了 显示找不到./data/order.csv

**Comment by Krstar233** [comment]
@mosquitokevin 看看是否没有配置python环境？

**Comment by Krstar233** [comment]
可以给出详细的报错信息吗？

**Comment by mosquitokevin** [comment]
@Krstar233 
"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe" C:\Users\HUAWEI\Desktop\IceWineManageSystem-main\demo\data\readcsv.py 
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\IceWineManageSystem-main\demo\data\readcsv.py", line 4, in <module>
    with open(fileHeader+'.csv')as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/order.csv'

进程已结束,退出代码1

**Comment by mosquitokevin** [comment]
我Python的环境目前就是只使用了SDK的Python3.9 不知道还应该再配什么

**Comment by Krstar233** [comment]
这个仓库很久没有维护了，我重新安装下环境看下哈

**Comment by mosquitokevin** [comment]
好的好的 真是麻烦大佬了 感谢感谢

**Comment by mosquitokevin** [comment]
我现在在python官网下载一下环境试试

**Comment by Krstar233** [comment]
@mosquitokevin 同学我更新了 Windows 环境的配置指引哈 https://github.com/Krstar233/IceWineManageSystem/blob/main/doc/env_windows.md
如果有问题麻烦继续在 issue 反馈哈

**Comment by mosquitokevin** [comment]
@Krstar233 真是太感谢你了 成功调试出来了 万分感谢

**Comment by Krstar233** [comment]
不客气哈~
